### ISSUE TITLE
Connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by marakas592** [georgewoodall82/Adv3GUI#11]
Hello, i using my old flashforge finder and tried to use your software. I think it works but with issues: after few seconds after connect it put in terminal this:

`C:\Users\user\Desktop\Adv3GUI-main>python Adv3GUI.py
Adv3GUI Starting
Adv3GUI Started!
Connected
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Adv3GUI-main\Adv3GUI.py", line 67, in <lambda>
    GCodeSend = tk.Button(root, text="Send", bg='#2f2f2f', fg='#ffffff', command=lambda: sendGCode(GCodeBox.get()))
                                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Adv3GUI-main\Adv3GUI.py", line 34, in sendGCode
    output(Adv3Api.SendGCode(gcode))
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Adv3GUI-main\Adv3Api.py", line 22, in SendGCode
    return SendTCP(gcode)
           ^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Adv3GUI-main\Adv3Api.py", line 27, in SendTCP
    socket1.send(data.encode())
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine`

![image](https://github.com/georgewoodall82/Adv3GUI/assets/127917462/34fa52eb-86f8-4e3a-94be-b1dd1d2a3f88)

Also if i try to send G28 command (home), your program returns output: ok, but nothing happens, printer not moving. Hope this helps.

**Comment by georgewoodall82** [comment]
I just updated it so that it connects every time a command is sent and disconnects afterwards. maybe this will fix the issue. It also includes a new file called Adv3CLI.py that runs in the terminal which I personally prefer as this is exactly what the terminal was made for.

Also for the G28 command not working, it is the exact same with me. For some reason this was broken in a recent update to printers. And for me I cant even home using flashprint.

To update just download the zip and extract again (replace all files) or git clone/pull.

Hope this fixes your issue, I have no idea if it will though.

**Comment by marakas592** [comment]
Wow, really fast answer and fix. Even faster than lighting 😄 So your fix works well, now connection not breaking.

Also about G28 command, it's happens after printer firmware update or Flashprint update?

**Comment by georgewoodall82** [comment]
Thanks, the G28 command broke after a printer firmware update.
